# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Goradar < Formula
  desc "A CLI tool for tracking aircraft using the adsb.lol API"
  homepage "https://github.com/alexraskin/goradar"
  version "1.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/alexraskin/goradar/releases/download/v1.0.1/goradar_Darwin_x86_64.tar.gz"
      sha256 "0fe01373884527bf46054b9693e0da8638e0c17ec7cb9c393441c2a4e46e20d7"

      def install
        bin.install "goradar"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/alexraskin/goradar/releases/download/v1.0.1/goradar_Darwin_arm64.tar.gz"
      sha256 "3720a3d78a9fcc3df106f600accdcfa6a484bfcd618203448e857c1c0ab74a92"

      def install
        bin.install "goradar"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/alexraskin/goradar/releases/download/v1.0.1/goradar_Linux_x86_64.tar.gz"
        sha256 "4aecc7d77829b37cfce51f2b274866ab71d0c59a719e392899432844656aa61a"

        def install
          bin.install "goradar"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/alexraskin/goradar/releases/download/v1.0.1/goradar_Linux_arm64.tar.gz"
        sha256 "3ef4b6a0ae1b571c33b9b0f9f0ad06f9d08839f555e0d1cca680c80aa77b62d6"

        def install
          bin.install "goradar"
        end
      end
    end
  end
end
